apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: publisher
    app.kubernetes.io/name: spring-sensors-publisher
    app.kubernetes.io/part-of: spring-sensors
  name: spring-sensors-publisher
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-sensors-publisher
  template:
    metadata:
      labels:
        app.kubernetes.io/component: publisher
        app.kubernetes.io/name: spring-sensors-publisher
        app.kubernetes.io/part-of: spring-sensors
    spec:
      containers:
      - env:
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        - name: PORT
          value: "8080"
        image: REGISTRY/PROJECT/spring-sensors-publisher:latest
        name: publisher
        ports:
        - containerPort: 8080
          name: user-port
          protocol: TCP
        volumeMounts:
        - mountPath: /bindings/rmq
          name: binding-rmq-1
          readOnly: true
      terminationGracePeriodSeconds: 300
      volumes:
      - name: binding-rmq-1
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: rmq-1-default-user
